### ISSUE TITLE
想咨询关于elastalert的几个问题

### ISSUE THREAD

**Issue by wajika** [JohnZhongg/azhong.github.io#2]
我看了你的文章，对于你解释的内容有几个疑问
owner
priority
category
description
这几个关键变量是怎么用的？你有理解文档的意思吗？可否举几个例子 我没理解文档里说的。

另外我很想实现一个每周总结报告
我有份后端http的数据，我想统计每个服务和它的接口的使用情况
```
+----------------------+-----------------------------------------------+-------+
|     service.name     |                   url.path                    | count |
| USER-login | /api/Account/getMiniToken | 1     |
| USER-edit| /api/Account/Token | 2     |
| USER-delete| /api/Account/Token | 3     |
+----------------------+-----------------------------------------------+-------+
```
这样写逻辑对吗？ 我想不配置filter

```
aggregation:
  days: 7
aggregation_key: service.name
top_count_keys: ["service.name", "url.path"]
summary_table_fields:
    - service.name
    - url.path
```

**Comment by wajika** [comment]
```
ERROR:elastalert:Traceback (most recent call last):
  File "C:\Users\AppData\Local\Programs\Python\Python39\lib\site-packages\elastalert2-2.2.1-py3.9.egg\elastalert\elastalert.py", line 1542, in alert
    return self.send_alert(matches, rule, alert_time=alert_time, retried=retried)
  File "C:\Users\AppData\Local\Programs\Python\Python39\lib\site-packages\elastalert2-2.2.1-py3.9.egg\elastalert\elastalert.py", line 1577, in send_alert
    counts = self.get_top_counts(rule, start, end, keys, qk=qk)
  File "C:\Users\AppData\Local\Programs\Python\Python39\lib\site-packages\elastalert2-2.2.1-py3.9.egg\elastalert\elastalert.py", line 2091, in get_top_counts
    hits_terms = self.get_hits_terms(rule, starttime, endtime, index, key, qk, number)
  File "C:\Users\AppData\Local\Programs\Python\Python39\lib\site-packages\elastalert2-2.2.1-py3.9.egg\elastalert\elastalert.py", line 543, in get_hits_terms
    res = self.thread_data.current_es.deprecated_search(index=index, doc_type=rule['doc_type'],
KeyError: 'doc_type'

ERROR:elastalert:Uncaught exception running rule Test: 'doc_type'

ERROR:elastalert:Traceback (most recent call last):
  File "c:\Users\Documents\python\elastalert2\elastalert\elastalert.py", line 1542, in alert
    return self.send_alert(matches, rule, alert_time=alert_time, retried=retried)
  File "c:\Users\Documents\python\elastalert2\elastalert\elastalert.py", line 1577, in send_alert
    counts = self.get_top_counts(rule, start, end, keys, qk=qk)
  File "c:\Users\Documents\python\elastalert2\elastalert\elastalert.py", line 2091, in get_top_counts
    hits_terms = self.get_hits_terms(rule, starttime, endtime, index, key, qk, number)
  File "c:\Users\Documents\python\elastalert2\elastalert\elastalert.py", line 559, in get_hits_terms
    self.thread_data.num_hits += len(buckets)
AttributeError: '_thread._local' object has no attribute 'num_hits'

```

```
name: 'Test'
type: any
#index: apm-*-error-*
index: apm-*-transaction-*
num_hits: 1
#aggregation:
#  schedule: '*/30 * * * *'
aggregation:
  minutes: 1
aggregation_key: "http.response.status_code"
summary_table_fields:
  - service.name
  - url.path
  - http.response.status_code
top_count_keys: ["service.name", "url.path", "http.response.status_code"]
top_count_number: 100
filter:
- term:
    http.response.status_code: "500"
doc_type: _doc

alert_text: "{},{}"
alert_text_args:
  - aggregation_summary
  - num_hits
alert_text_type: aggregation_summary_only

smtp_host: smtp.partner.outlook.cn
smtp_port: 587
smtp_auth_file: "C:\\Users\\Documents\\python\\elastalert2\\rules\\user.yml"
from_addr: "noreply@xxx.cn"
alert:
  - "email"
email:
  - "xxx@xxx.cn"
email_format: html
```
另外这种问题该怎么调试？你有思路吗？

关于'_thread._local' object has no attribute 'num_hits'的问题，我在alert_text_args: 里增加- num_hits好像就没提示错误了
关于 Uncaught exception running rule Test: 'doc_type' 的问题，我加上doc_type: _doc 也解决了
但是我不知道从代码的角度为什么会报错？
